sparse-checkout for git-get when no DIR

diff --git a/git-get b/git-get
--- a/git-get
+++ b/git-get
@@ -70,6 +70,7 @@ PRESERVE=
 TAG=
 TAG_FILE=
 DIR=
+SPARSE=
 CL_BRANCHES=
 CL_TAGS=
 POSITIONAL=()
@@ -221,7 +222,15 @@ if [ -n "$PRESERVE" ] && [ -n "$TAG" ]; then
     exit 1
 fi
 if [ -n "$PRESERVE" ] && [ -n "$DIR" ]; then
-    echo "Error: Conflict: -x|-g|--preserve-git and -- <path>" >&2
+    echo "${C_ERR}Error: Conflict: -x|-g|--preserve-git and -- <path>${C_RST}" >&2
+    echo "${C_NOTICE}Hint: You may consider git-get the whole repo with -- option first:" >&2
+    echo "          git get [-x|-g] [<options>] <repo> --" >&2
+    echo "      and then manually:" >&2
+    echo "          git sparse-checkout add $DIR${C_RST}" >&2
+    exit 1
+fi
+if [ -z "$PRESERVE" ] && [ -n "$SPARSE" ]; then
+    echo "${C_ERR}Error: Conflict: -- requires -x|-g|--preserve-git${C_RST}" >&2
     exit 1
 fi
 if [ -n "$GH_USE_HTTPS" ] && [ -n "$GH_USE_SSH" ]; then
@@ -397,6 +406,10 @@ match_gh_url "https://github.com/" '' resolve_gh_url ||
 
 if [ -n "$PRESERVE" ] && [ -n "$DIR" ]; then
     echo "${C_ERR}Error: Can't use an URL (of a folder or file) with -x|-g|--preserve-git${C_RST}" >&2
+    echo "${C_NOTICE}Hint: You may consider git-get the whole repo with -- option first:" >&2
+    echo "          git get [-x|-g] [<options>] <repo> --" >&2
+    echo "      and then manually:" >&2
+    echo "          git sparse-checkout add $DIR${C_RST}" >&2
     exit 1
 fi
 
@@ -465,6 +478,7 @@ if [ -n "$VERBOSE" ]; then
     printf "${C_DBG}REPO=%q${C_RST}\n" "$REPO" >&2
     printf "${C_DBG}BRANCH=%q${C_RST}\n" "$BRANCH" >&2
     printf "${C_DBG}DIR=%q${C_RST}\n" "$DIR" >&2
+    printf "${C_DBG}SPARSE=%q${C_RST}\n" "$SPARSE" >&2
     printf "${C_DBG}BASENAME=%q${C_RST}\n" "$BASENAME" >&2
     printf "${C_DBG}PREV_TAGS=%q${C_RST}\n" "$PREV_TAGS" >&2
 fi
@@ -648,6 +662,13 @@ got_repo() {
             fi
         fi
         unset GIT_DIR
+        if [ -n "$SPARSE" ]; then
+            ARGS=(git sparse-checkout set --sparse-index --cone)
+            [ -n "$QUIET" ] && ARGS+=(-q)
+            [ -n "$VERBOSE" ] && (printf "${C_NOTICE}" >&2; printf '%q ' "${ARGS[@]}" >&2; printf "${C_RST}\n">&2)
+            [ -z "$QUIET" ] && (cd "$1" && "${ARGS[@]}" >&2)
+            [ -n "$QUIET" ] && (cd "$1" && "${ARGS[@]}" 2>/dev/null >&2)
+        fi
         ARGS=(git reset --hard)
         [ -n "$QUIET" ] && ARGS+=(-q)
         [ -n "$VERBOSE" ] && (printf "${C_NOTICE}" >&2; printf '%q ' "${ARGS[@]}" >&2; printf "${C_RST}\n">&2)
@@ -764,7 +785,9 @@ if git_new; then
         [ -z "$QUIET" ] && ARGS+=(--progress)
         [ ! "$BRANCH" = "HEAD" ] && ARGS+=(--branch "$BRANCH")
         ARGS+=(--depth 1 --no-tags)
-        [ -n "$DIR" ] && ARGS+=(--filter blob:none)
+        if [ -n "$DIR" ] || [ -n "$SPARSE" ]; then
+            ARGS+=(--filter blob:none)
+        fi
         ARGS+=("$REPO" "$BASENAME/.git")
         [ -n "$VERBOSE" ] && (printf "${C_NOTICE}" >&2; printf '%q ' "${ARGS[@]}" >&2; printf "${C_RST}\n">&2)
         set +e
