add gist.github.com support
Fix #5.
Now, even if you type https://[gist.]github.com/... as URL,
ssh will still be used unless you specify -H|--https

diff --git a/git-get b/git-get
--- a/git-get
+++ b/git-get
@@ -216,7 +216,7 @@ resolve_gh_url() {
         AMBI=VERY_MUCH
     elif grep -qP '^[^/]+/[^/]+/blob/' <<<"$1"; then
         if [ -n "$PRESERVE" ]; then
-            echo "Error: Conflict: -g|--preserve-git and -- <path> (in the URL)" >&2
+            echo "Error: Conflict: -x|-g|--preserve-git and -- <path> (in the URL)" >&2
             exit 1
         fi
         if [ "${#POSITIONAL[@]}" -ne 1 ]; then
@@ -231,7 +231,7 @@ resolve_gh_url() {
         exit 1
     fi
 
-    if [ -n "$2" ] && [ -n "$GH_USE_SSH" ] || [ -n "$GH_USE_HTTPS" ]; then
+    if [ -n "$GH_USE_HTTPS" ]; then
         REPO="https://github.com/$GH_REPO.git"
     else
         REPO="git@github.com:$GH_REPO.git"
@@ -249,9 +249,34 @@ resolve_gh_url() {
     unset AMBI
 }
 
+resolve_gist_url() {
+    GITHUB=GIST
+    BRANCH=master
+    DIR=
+    if [[ "$1" =~ \#file- ]]; then
+        DIR="${1#*#file-}"
+        GH_REPO="${1%%#*}"
+    else
+        GH_REPO="$1"
+    fi
+    if [[ "$GH_REPO" =~ / ]]; then
+        GH_REPO="${GH_REPO#*/}"
+    fi
+    if [[ "$GH_REPO" =~ / ]]; then
+        echo "Error: GitHub Gist URL format not supported" >&2
+        exit 1
+    fi
+
+    if [ -n "$GH_USE_HTTPS" ]; then
+        REPO="https://gist.github.com/$GH_REPO.git"
+    else
+        REPO="git@gist.github.com:$GH_REPO.git"
+    fi
+}
+
 match_gh_url() {
     [[ ! "${POSITIONAL[0]}" =~ ^$1 ]] && return 1
-    [ -z "$2" ] && [ -z "$QUIET" ] && echo "Warning: $1 is an unencryped protocol" >&2
+    [ -n "$2" ] && [ -z "$QUIET" ] && echo "Warning: $1 is an unencryped protocol" >&2
     if [ -n "$3" ]; then
         "$3" "${POSITIONAL[0]#${1}}" YES
     else
@@ -259,13 +284,33 @@ match_gh_url() {
         GH_REPO="${POSITIONAL[0]#${1}}"
         GH_REPO="${GH_REPO%/}"
         GH_REPO="${GH_REPO%.git}"
+        if [ -n "$GH_USE_HTTPS" ]; then
+            REPO="https://github.com/$GH_REPO.git"
+        elif [ -n "$GH_USE_SSH" ]; then
+            REPO="git@github.com:$GH_REPO.git"
+        else
+            REPO="$1$GH_REPO.git"
+        fi
     fi
-    if [ -n "$GH_USE_HTTPS" ]; then
-        REPO="https://github.com/$GH_REPO.git"
-    elif [ -n "$GH_USE_SSH" ]; then
-        REPO="git@github.com:$GH_REPO.git"
+}
+
+match_gist_url() {
+    [[ ! "${POSITIONAL[0]}" =~ ^$1 ]] && return 1
+    [ -n "$2" ] && [ -z "$QUIET" ] && echo "Warning: $1 is an unencryped protocol" >&2
+    if [ -n "$3" ]; then
+        "$3" "${POSITIONAL[0]#${1}}"
     else
-        REPO="$1$GH_REPO.git"
+        GITHUB=GIST
+        GH_REPO="${POSITIONAL[0]#${1}}"
+        GH_REPO="${GH_REPO%/}"
+        GH_REPO="${GH_REPO%.git}"
+        if [ -n "$GH_USE_HTTPS" ]; then
+            REPO="https://gist.github.com/$GH_REPO.git"
+        elif [ -n "$GH_USE_SSH" ]; then
+            REPO="git@gist.github.com:$GH_REPO.git"
+        else
+            REPO="$1$GH_REPO.git"
+        fi
     fi
 }
 
@@ -274,7 +319,12 @@ match_gh_url "https://github.com/" '' resolve_gh_url ||
     match_gh_url "git://github.com/" YES '' ||
     match_gh_url "ssh://git@github.com/" '' '' ||
     match_gh_url "git@github.com:" '' '' ||
-    if [[ "${POSITIONAL[0]}" =~ : ]]; then
+    match_gist_url "https://gist.github.com/" '' resolve_gist_url ||
+    match_gist_url "http://gist.github.com/" YES resolve_gist_url ||
+    match_gist_url "git://gist.github.com/" YES '' ||
+    match_gist_url "ssh://git@gist.github.com/" '' '' ||
+    match_gist_url "git@gist.github.com:" '' '' ||
+    if [[ "${POSITIONAL[0]}" =~ : ]] || [[ "${POSITIONAL[0]}" =~ ^\. ]]; then
         GITHUB=
         GH_REPO=
         REPO="${POSITIONAL[0]}"
@@ -291,6 +341,8 @@ DIR="$(normalize "$DIR")"
 
 if [ -n "$DIR" ]; then
     BASENAME="$(basename "$DIR")"
+elif [ "$GITHUB" = GIST ]; then
+    BASENAME="$GH_REPO"
 else
     BASENAME="$(basename "$REPO")"
     BASENAME="${BASENAME%.git}"
